<script setup>
import { Head, Link } from '@inertiajs/vue3';
import ParticipantLayout from '@/Layouts/ParticipantLayout.vue';

const props = defineProps({
    certificates: Array,
    isEligible: Boolean,
    hasUploadedCert: Boolean,
    registrationStatus: String,
    activeConference: Object,
});
</script>

<template>
    <Head title="My E-Certificates - ICHA 2026" />

    <ParticipantLayout>
        <div class="max-w-5xl mx-auto space-y-6">
            
            <!-- Header Banner -->
            <div class="bg-white rounded-3xl p-6 lg:p-8 shadow-sm border border-slate-100 flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 class="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
                        <span class="text-2xl">🎓</span>
                        My Official E-Certificates
                    </h1>
                    <p class="text-xs text-slate-500 mt-1">Download official verified electronic certificates for conference participation and presentations.</p>
                </div>
                <div v-if="props.hasUploadedCert" class="px-3.5 py-1.5 rounded-full bg-emerald-50 text-emerald-700 text-xs font-bold border border-emerald-200 inline-flex items-center gap-1.5 self-start md:self-auto">
                    <span class="h-2 w-2 rounded-full bg-emerald-500"></span>
                    Certificate Ready for Download
                </div>
            </div>

            <!-- Ineligible Notice (Not paid & no accepted abstract) -->
            <div v-if="!props.isEligible" class="bg-amber-50 rounded-3xl p-6 border border-amber-200 text-amber-950 flex flex-col md:flex-row items-center justify-between gap-4">
                <div class="flex items-center gap-4">
                    <div class="w-12 h-12 rounded-2xl bg-amber-100 flex items-center justify-center shrink-0 text-xl font-bold">
                        🔒
                    </div>
                    <div>
                        <h3 class="font-bold text-sm">Certificate Download Locked</h3>
                        <p class="text-xs text-amber-800/80 mt-0.5">E-Certificates are unlocked upon completing verified paid conference registration or having an accepted presentation abstract.</p>
                    </div>
                </div>
                <Link
                    :href="route('participant.registration.create')"
                    class="px-5 py-2.5 rounded-xl bg-gold hover:bg-amber-400 text-slate-950 font-bold text-xs shadow-sm transition whitespace-nowrap"
                >
                    Complete Registration &rarr;
                </Link>
            </div>

            <!-- Eligible, but Admin has not uploaded certificate yet -->
            <div v-else-if="!props.certificates || props.certificates.length === 0" class="bg-purple-50/60 rounded-3xl p-8 border border-purple-200/80 text-center max-w-lg mx-auto space-y-3">
                <div class="w-14 h-14 rounded-2xl bg-purple-100 text-purple-800 flex items-center justify-center mx-auto text-2xl font-bold shadow-xs">
                    ⏳
                </div>
                <h3 class="text-base font-black text-purple-950">Certificate Under Preparation</h3>
                <p class="text-xs text-purple-900/80 leading-relaxed">
                    Your conference participation is verified. Official signed certificates are being generated by the committee and will be available for download here shortly.
                </p>
                <div class="pt-2">
                    <span class="inline-block px-3 py-1 rounded-full bg-purple-100 text-purple-800 font-bold text-[11px]">
                        Conference: {{ props.activeConference?.title || 'ICHA 2026' }}
                    </span>
                </div>
            </div>

            <!-- Certificates Grid -->
            <div v-else class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div
                    v-for="cert in props.certificates"
                    :key="cert.id"
                    class="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 flex flex-col justify-between space-y-6 relative overflow-hidden group hover:shadow-xl transition-all"
                >
                    <div class="absolute -right-8 -top-8 w-28 h-28 bg-purple-50 rounded-full group-hover:scale-150 transition-transform duration-500"></div>

                    <div class="relative z-10 space-y-3">
                        <div class="flex items-center justify-between">
                            <span class="px-3 py-1 rounded-full bg-purple-100 text-purple-800 text-[10px] font-black uppercase tracking-wider">
                                🎓 Official E-Certificate
                            </span>
                            <span class="font-mono text-[11px] font-bold text-slate-400">{{ cert.certificate_number }}</span>
                        </div>

                        <h3 class="text-base font-black text-slate-900 leading-snug">{{ cert.role_title }}</h3>
                        <p class="text-xs text-slate-500">{{ cert.conference?.title || 'ICHA 2026 Conference' }}</p>
                    </div>

                    <div class="relative z-10 pt-4 border-t border-slate-100 flex items-center justify-between gap-3">
                        <span class="text-[10px] text-slate-400 font-medium">
                            Issued: {{ new Date(cert.issued_at).toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' }) }}
                        </span>

                        <!-- Download Uploaded PDF -->
                        <a
                            v-if="cert.file_url"
                            :href="cert.file_url"
                            target="_blank"
                            download
                            class="inline-flex items-center gap-1.5 bg-gold hover:bg-gold-dark text-slate-950 font-black text-xs py-2.5 px-4 rounded-xl shadow-md transition cursor-pointer"
                        >
                            <span>📥</span>
                            Download Official PDF
                        </a>

                        <!-- Fallback view printable HTML -->
                        <a
                            v-else
                            :href="route('certificate.download', cert.id)"
                            target="_blank"
                            class="inline-flex items-center gap-1.5 bg-primary hover:bg-primary-dark text-white font-bold text-xs py-2 px-4 rounded-xl shadow-sm transition cursor-pointer"
                        >
                            <span>🖨️</span>
                            View E-Certificate
                        </a>
                    </div>
                </div>
            </div>

        </div>
    </ParticipantLayout>
</template>
